[project]
name = "PyCFF"
version = "1.1.5"
description = "A function fitting tool"
authors = [{ name = "Andrew Moa", email = "Andrew.Moa2005@163.com" }]
license = "LGPL-3.0-or-later"
keywords = ["PySide6", "application", "widget"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Applications :: Python",
]
dependencies = ["numpy>=1.26.0", "scipy>=1.12.0", "pyside6>=6.6.0"]

[tool.pyside6-project]
files = [
    "resource.qrc",
    "application.py",
    "form.ui",
    "widget.py",
    "clevertw.py",
    "cff.py",
]
